[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=6.0.0",
    "pandas>=2.3.1",
    "tqdm>=4.67.1",
    "matplotlib>=3.9.0",
    "jupyter>=1.1.1",
    "notebook>=7.4.5",
    "ipykernel>=6.30.1",
    "upsetplot>=0.9.0",
]

[dependency-groups]
dev = [
    "black[jupyter]>=25.1.0",
    "pytest>=8.4.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.12.10",
    "ty>=0.0.1a20",
]

[tool.pytest.ini_options]
pythonpath = ["."]
python_files = "avp/*.py test_*.py *_test.py"

[tool.ty.rules]
possibly-unbound-import = "ignore" # false-positives
possibly-unbound-attribute = "ignore" # false-positives: https://github.com/astral-sh/ty/issues/479
